spring:
  datasource:
    url: jdbc:mysql://localhost:3306/desafio_fullstack?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 161283
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    

  data:
    web:
      pageable:
        page-parameter: page
        size-parameter: size
        default-page-size: 10
        max-page-size: 100
      sort:
        sort-parameter: sort
  jackson:
    serialization:
       write-dates-as-timestamps: false
       fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non-null
    