spring:
  datasource:
    url: jdbc:mysql://localhost:3306/desafio_fullstack?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 161283
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
